In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from src.data.market_loader import MarketLoader

from src.curves.curve_snapshot import CurveSnapshot
from src.curves.base_curve import BaseCurve

In [2]:
# downloading market curves
loader = MarketLoader()

market_curves = loader.market_loader_pipeline()
market_curves

Downloading treasury curve from FRED..
Downloading sofr curve from FRED..
Downloading futures curve from FRED..
Downloadingestr curve from ECB

           treasury                                            sofr futures  \
                 1M    3M    6M    1Y    2Y    5Y   10Y   30Y    ON      3M
Date
2019-10-01     1.79  1.82  1.81  1.73  1.56  1.51  1.65  2.11  1.88    1.78
2019-10-02     1.75  1.79  1.75  1.67  1.48  1.43  1.60  2.09  1.85    1.75
2019-10-03     1.78  1.70  1.66  1.58  1.39  1.34  1.54  2.04  1.84    1.67
2019-10-04     1.73  1.71  1.65  1.58  1.40  1.34  1.52  2.01  1.82    1.68
2019-10-07     1.76  1.75  1.73  1.64  1.46  1.38  1.56  2.05  1.83    1.71
...             ...   ...   ...   ...   ...   ...   ...   ...   ...     ...
2026-05-25     3.72  3.68  3.79  3.86  4.13  4.27  4.56  5.07  3.55    3.59
2026-05-26     3.72  3.68  3.80  3.82  4.01  4.19  4.50  5.03  3.63    3.60
2026-05-27     3.72  3.68  3.79  3.80  4.00  4.17  4.48  5.01  3.63    3.59
2026-05-28     3.72  3.69  3.79  3.80  3.99  4.15  4.45  4.98  3.62    3.60
2026-05-29     3.72  3.69  3.79  3.80  3.99  4.15  4.45  4.98  3.62    3.60

                   estr
              6M   ESTR
Date
2019-10-01  1.76 -0.549
2019-10-02  1.71 -0.551
2019-10-03  1.62 -0.555
2019-10-04  1.61 -0.553
2019-10-07  1.69 -0.554
...          ...    ...
2026-05-25  3.64  1.931
2026-05-26  3.65  1.932
2026-05-27  3.64  1.932
2026-05-28  3.64  1.933
2026-05-29  3.64  1.930

[1739 rows x 12 columns]

In [3]:
# summary statistics
market_curves.describe().T

                count      mean       std    min    25%    50%    75%    max
treasury 1M    1739.0  2.803732  2.194154  0.000  0.100  3.720  4.660  6.020
         3M    1739.0  2.863864  2.170811  0.000  0.135  3.690  4.730  5.630
         6M    1739.0  2.888281  2.110886  0.020  0.175  3.730  4.760  5.610
         1Y    1739.0  2.828522  1.988348  0.040  0.210  3.630  4.620  5.490
         2Y    1739.0  2.751984  1.796562  0.090  0.500  3.570  4.260  5.190
         5Y    1739.0  2.777062  1.531798  0.190  1.150  3.610  4.030  4.950
         10Y   1739.0  2.995779  1.392559  0.520  1.590  3.660  4.230  4.980
         30Y   1739.0  3.388746  1.264242  0.990  2.110  3.780  4.590  5.180
sofr     ON    1739.0  2.754733  2.140719  0.010  0.090  3.650  4.600  5.400
futures  3M    1739.0  2.762806  2.083708 -0.050  0.135  3.600  4.555  5.360
         6M    1739.0  2.785566  2.026463  0.020  0.175  3.600  4.595  5.360
estr     ESTR  1739.0  1.285737  1.767296 -0.593 -0.557  1.905  2.919  3.913

In [4]:
# curve snapshot of a given date
treasury_df = market_curves['treasury']

latest_date = treasury_df.index[-1]
latest_curve = treasury_df.iloc[-1]

snapshot = CurveSnapshot.snap_from_df_row(
    curve_name = 'treasury',
    as_of_date = latest_date,
    curve_row = latest_curve
)

display(snapshot.summary())

# linear interpolated base curve object
base_curve = BaseCurve(
    curve_snapshot = snapshot,
    interpolation_method = 'linear'
)

base_curve

  Tenor      Years  Rate
0    1M   0.083333  3.72
1    3M   0.250000  3.69
2    6M   0.500000  3.79
3    1Y   1.000000  3.80
4    2Y   2.000000  3.99
5    5Y   5.000000  4.15
6   10Y  10.000000  4.45
7   30Y  30.000000  4.98

BaseCurve(curve_name=treasury, as_of_date=2026-05-29 00:00:00, tenor_length=8, interpolation=linear)

In [5]:
# downloading swap curves
swap_curves = loader.swap_loader_pipeline()
swap_curves

usd_ois curve dataset already downloaded..
eur_ois curve dataset already downloaded..

           usd_ois                                                        \
                1Y    2Y    3Y    4Y    5Y    7Y   10Y   15Y   20Y   30Y
Date
2026-05-29    3.82  3.86  3.85  3.86  3.87  3.93  4.03  4.21  4.28  4.26

           eur_ois
                1Y    2Y    3Y    4Y    5Y    7Y   10Y   15Y   30Y
Date
2026-05-29    2.41  2.44  2.45  2.48  2.52  2.61  2.77  2.98  3.04

In [6]:
# curve snapshot of a given date
usd_ois = swap_curves['usd_ois']
latest_date = usd_ois.index[-1]

latest_curve = usd_ois.iloc[-1]

swap_snapshot = CurveSnapshot.snap_from_df_row(
    curve_name="usd_ois",
    as_of_date=latest_date,
    curve_row=latest_curve
)

display(swap_snapshot.summary())

# linear interpolated base curve object
ois_curve = BaseCurve(
    curve_snapshot=swap_snapshot,
    interpolation_method="linear"
)

ois_curve

  Tenor  Years  Rate
0    1Y    1.0  3.82
1    2Y    2.0  3.86
2    3Y    3.0  3.85
3    4Y    4.0  3.86
4    5Y    5.0  3.87
5    7Y    7.0  3.93
6   10Y   10.0  4.03
7   15Y   15.0  4.21
8   20Y   20.0  4.28
9   30Y   30.0  4.26

BaseCurve(curve_name=usd_ois, as_of_date=2026-05-29 00:00:00, tenor_length=10, interpolation=linear)