In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

import pandas as pd
import matplotlib.pyplot as plt

from src.data.market_loader import MarketLoader

In [ ]:
# downloading market curves
loader = MarketLoader()

curves = loader.loader_pipeline()
curves

Downloading treasury curve from FRED..
Downloading sofr curve from FRED..
Downloading futures curve from FRED..
Downloadingestr curve from ECB

           treasury                                            sofr           \
                 1M    3M    6M    1Y    2Y    5Y   10Y   30Y    ON FEDFUNDS
Date
2019-10-01     1.79  1.82  1.81  1.73  1.56  1.51  1.65  2.11  1.88     1.88
2019-10-02     1.75  1.79  1.75  1.67  1.48  1.43  1.60  2.09  1.85     1.85
2019-10-03     1.78  1.70  1.66  1.58  1.39  1.34  1.54  2.04  1.84     1.83
2019-10-04     1.73  1.71  1.65  1.58  1.40  1.34  1.52  2.01  1.82     1.82
2019-10-07     1.76  1.75  1.73  1.64  1.46  1.38  1.56  2.05  1.83     1.82
...             ...   ...   ...   ...   ...   ...   ...   ...   ...      ...
2026-05-22     3.72  3.68  3.79  3.86  4.13  4.27  4.56  5.07  3.55     3.62
2026-05-25     3.72  3.68  3.79  3.86  4.13  4.27  4.56  5.07  3.55     3.62
2026-05-26     3.72  3.68  3.80  3.82  4.01  4.19  4.50  5.03  3.63     3.62
2026-05-27     3.72  3.68  3.79  3.80  4.00  4.17  4.48  5.01  3.63     3.62
2026-05-28     3.72  3.68  3.79  3.80  4.00  4.17  4.48  5.01  3.63     3.62

           futures           estr
           TBill3M TBill6M   ESTR
Date
2019-10-01    1.78    1.76 -0.549
2019-10-02    1.75    1.71 -0.551
2019-10-03    1.67    1.62 -0.555
2019-10-04    1.68    1.61 -0.553
2019-10-07    1.71    1.69 -0.554
...            ...     ...    ...
2026-05-22    3.59    3.64  1.929
2026-05-25    3.59    3.64  1.931
2026-05-26    3.60    3.65  1.932
2026-05-27    3.59    3.64  1.932
2026-05-28    3.59    3.64  1.933

[1738 rows x 13 columns]

In [3]:
# summary statistics
curves.describe().T

                    count      mean       std    min     25%     50%     75%  \
treasury 1M        1738.0  2.803205  2.194676  0.000  0.1000  3.7200  4.6600
         3M        1738.0  2.863383  2.171343  0.000  0.1325  3.6900  4.7300
         6M        1738.0  2.887762  2.111383  0.020  0.1725  3.7300  4.7600
         1Y        1738.0  2.827963  1.988784  0.040  0.2100  3.6300  4.6200
         2Y        1738.0  2.751277  1.796837  0.090  0.5000  3.5700  4.2600
         5Y        1738.0  2.776283  1.531895  0.190  1.1500  3.6100  4.0300
         10Y       1738.0  2.994960  1.392541  0.520  1.5900  3.6550  4.2300
         30Y       1738.0  3.387848  1.264051  0.990  2.1100  3.7800  4.5900
sofr     ON        1738.0  2.754241  2.141237  0.010  0.0900  3.6500  4.6000
         FEDFUNDS  1738.0  2.765150  2.129549  0.040  0.0900  3.6400  4.5800
futures  TBill3M   1738.0  2.762319  2.084209 -0.050  0.1325  3.6000  4.5575
         TBill6M   1738.0  2.785075  2.026942  0.020  0.1725  3.6000  4.5975
estr     ESTR      1738.0  1.285367  1.767737 -0.593 -0.5570  1.9045  2.9190

                     max
treasury 1M        6.020
         3M        5.630
         6M        5.610
         1Y        5.490
         2Y        5.190
         5Y        4.950
         10Y       4.980
         30Y       5.180
sofr     ON        5.400
         FEDFUNDS  5.330
futures  TBill3M   5.360
         TBill6M   5.360
estr     ESTR      3.913